# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleareafinca',
            name='seleccion',
            field=models.IntegerField(choices=[(1, 'Bosque'), (2, 'Tacotal o regeneraci\xf3n natural'), (3, 'Cultivo anual (que produce en el a\xf1o)'), (4, 'Plantaci\xf3n forestal (madera y le\xf1a)'), (5, '\xc1rea de pastos abierto'), (6, '\xc1rea de pastos con \xe1rboles'), (7, 'Cultivo perenne (frutales)'), (8, 'Cultivo semi-perenne (mus\xe1cea, pi\xf1a)'), (9, 'Solo destinado para cacao'), (10, 'Huerto mixto con cacao'), (11, 'Otros')], verbose_name='3.2 Distribuci\xf3n de la finca'),
        ),
    ]
