# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0003_auto_20150804_1931'),
        ('productores', '0002_auto_20160704_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacionterreno',
            name='textura_suelo',
            field=models.IntegerField(choices=[(1, 'Arcilloso'), (2, 'Limoso'), (3, 'Arenoso'), (4, 'Franco'), (5, 'Franco Arenoso')], verbose_name='\xbfCu\xe1l es el tipo de textura del suelo?'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='paga_certificacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Productor'), (2, 'Mercado'), (3, 'Asociaci\xf3n Nacional'), (4, 'Cooperante'), (5, 'Organizaci\xf3n local')], null=True, verbose_name='\xbfQui\xe9n paga la certificaci\xf3n?'),
        ),
        migrations.RemoveField(
            model_name='comercializacioncacao',
            name='donde_vende',
        ),
        migrations.AddField(
            model_name='comercializacioncacao',
            name='donde_vende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio', verbose_name='\xbfD\xf3nde lo vende? Municipios'),
        ),
        migrations.AlterField(
            model_name='comercializacioncacao',
            name='producto',
            field=models.IntegerField(choices=[(1, 'Mazorca de cacao (unidad)'), (2, 'Semilla para siembra (unidad)'), (3, 'Cacao en baba (lb)'), (4, 'Cacao seco corriente (lb)'), (5, 'Cacao fermentado (lb)'), (6, 'Chocolate artesanal (lb)'), (7, 'Pinol (lb)'), (8, 'Cacao artesanal (lb)'), (9, 'Vino de cacao (lt)')]),
        ),
        migrations.AlterField(
            model_name='comercializacioncacao',
            name='quien_vende',
            field=models.IntegerField(blank=True, choices=[(1, 'Comunidad'), (2, 'Intermediario'), (3, 'Mercado'), (4, 'Cooperativa')], null=True, verbose_name='\xbfA qui\xe9n le vende?'),
        ),
        migrations.AlterField(
            model_name='detalleareafinca',
            name='seleccion',
            field=models.IntegerField(choices=[(1, 'Bosque'), (2, 'Guamil o regeneraci\xf3n natural'), (3, 'Cultivo anual (que produce en el a\xf1o)'), (4, 'Plantaci\xf3n forestal (madera y le\xf1a)'), (5, '\xc1rea de pastos abierto'), (6, '\xc1rea de pastos con \xe1rboles'), (7, 'Cultivo perenne (frutales)'), (8, 'Cultivo semi-perenne (mus\xe1cea, pi\xf1a)'), (9, 'Solo destinado para cacao'), (10, 'Huerto mixto con cacao'), (11, 'Otros')], verbose_name='3.2 Distribuci\xf3n de la finca'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='otros_ingresos',
            field=models.ManyToManyField(blank=True, to='productores.OtrosIngresos', verbose_name='Sobre otros Ingresos'),
        ),
        migrations.AlterField(
            model_name='mitigacionriesgos',
            name='si_tecnologia_secado',
            field=models.IntegerField(blank=True, choices=[(1, 'Propia'), (2, 'Cooperativa')], null=True, verbose_name='Si responde Si: favor indicar si la tecnolog\xeda de secado y almacenamiento es'),
        ),
        migrations.AlterField(
            model_name='mitigacionriesgos',
            name='si_venta_cacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'A trav\xe9s de la Cooperativa')], null=True, verbose_name='Si responde Si: favor indicar si el contrato lo hace'),
        ),
        migrations.AlterField(
            model_name='problemasareacacao',
            name='area_1',
            field=models.ManyToManyField(blank=True, to='productores.ProblemasArea1', verbose_name='En \xe1reas de 1 a 3 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='problemasareacacao',
            name='area_2',
            field=models.ManyToManyField(blank=True, to='productores.ProblemasArea2', verbose_name='En \xe1reas de 4 a 10 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='problemasareacacao',
            name='area_3',
            field=models.ManyToManyField(blank=True, to='productores.ProblemasArea3', verbose_name='En \xe1reas de 10 a 20 a\xf1os'),
        ),
    ]
