# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0004_auto_20160804_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionProduccionCacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(choices=[(0.1, '10%'), (0.2, '20%')])),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name': 'Producci\xf3n de cacao \xfaltimo a\xf1o',
                'verbose_name_plural': 'Producci\xf3n de cacao \xfaltimo a\xf1o',
            },
        ),
    ]
