# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0003_auto_20150804_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Organizaci\xf3n')),
                ('siglas', models.CharField(max_length=200)),
                ('fundacion', models.DateField(blank=True, null=True, verbose_name='A\xf1o de fundaci\xf3n')),
                ('gerente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Presidente/Administrador')),
                ('status', models.IntegerField(choices=[(1, 'ONG'), (2, 'Cooperativa'), (3, 'Uni\xf3n de Cooperativa')], verbose_name='Estatus Legal')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='N\xfamero telef\xf3nico')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de contacto')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logo/')),
                ('slug', models.SlugField(editable=False, max_length=450)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'verbose_name': 'Organizaci\xf3n',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
