# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercializacion',
            name='seleccion',
            field=models.IntegerField(choices=[(1, 'No. de socios que entregaron cacao al acopio'), (2, 'No. de No socios que entregaron cacao al acopio'), (3, 'Cantidad de cacao en baba acopiado por la organizaci\xf3n')]),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Bueno'), (2, 'Malo'), (3, 'Regular')], null=True, verbose_name='Estado mec\xe1nico de los medios'),
        ),
    ]
