# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_auto_20160609_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercializacion',
            name='no_socias_corriente',
            field=models.FloatField(verbose_name='Mujeres (Fermentado)'),
        ),
        migrations.AlterField(
            model_name='comercializacion',
            name='no_socios_corriente',
            field=models.FloatField(verbose_name='Hombres (Fermentado)'),
        ),
        migrations.AlterField(
            model_name='comercializacion',
            name='socias_corriente',
            field=models.FloatField(verbose_name='Mujeres (Corriente)'),
        ),
        migrations.AlterField(
            model_name='comercializacion',
            name='socios_corriente',
            field=models.FloatField(verbose_name='Hombres (Corriente)'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de elaboraci\xf3n o actualizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='status',
            field=models.IntegerField(choices=[(1, 'ONG'), (2, 'Cooperativa'), (3, 'Asociaci\xf3n'), (4, 'Proyectos')], verbose_name='Estatus Legal'),
        ),
    ]
