# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_escuelacampo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionComercializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField(verbose_name='Cantidad (lbs)')),
                ('estado', models.IntegerField(choices=[(1, 'Baba'), (2, 'Seco')])),
                ('tipo_cacao', models.IntegerField(choices=[(1, 'Convencional'), (2, 'T1'), (3, 'T2'), (4, 'T3'), (5, 'Ecol\xf3gico')])),
                ('calidad', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')])),
                ('precio', models.FloatField(blank=True, null=True)),
                ('mercado', models.IntegerField(choices=[(1, 'Intermediario local'), (2, 'APROCACAHO'), (3, 'Chocolats Halba'), (4, 'Otros')])),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.EncuestaOrganicacion')),
            ],
            options={
                'verbose_name_plural': 'Producci\xf3n y comercializaci\xf3n cacao',
            },
        ),
        migrations.RemoveField(
            model_name='cacaocomercializado',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='comercializacion',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='datosproductivos',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='datosproductivostabla',
            name='encuesta',
        ),
        migrations.AddField(
            model_name='listamiembros',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CacaoComercializado',
        ),
        migrations.DeleteModel(
            name='Comercializacion',
        ),
        migrations.DeleteModel(
            name='DatosProductivos',
        ),
        migrations.DeleteModel(
            name='DatosProductivosTabla',
        ),
    ]
